services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: preprod
    environment:
      APP_ENV: preprod
    volumes:
      - .:/var/www/app
      - /var/www/app/vendor

  nginx:
    ports:
      - "8080:80"

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-phone_management_preprod}
