services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"

  nginx:
    ports:
      - "80:80"

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-phone_management}
